carts/urls.py
from django.urls import path
from . import views


app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar',views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

facilito_store/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from products.views import ProductListView

urlpatterns = [
    path('',ProductListView.as_view(), name='index'),
    path('admin/', admin.site.urls),

    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos/', include('billing_profiles.urls')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name= 'order'),
    path('dirección', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds'),


]

promo_codes/urls.py
from django.urls import path
from . import views

app_name = 'promo_codes'

urlpatterns = [
    path('validar', views.validate, name='validate'),
]

shipping_addresses/urls.py
from django.urls import path
from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default'),
]

orders/models.py
import uuid
from django.db import models

from users.models import User
from carts.models import Cart
from shipping_addresses.models import ShippingAddress

from django.db.models.signals import pre_save

from .common import OrderStatus
from .common import choices
from promo_codes.models import PromoCode
import decimal

class Order(models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=choices,
                              default=OrderStatus.CREATED)  # enum
    shipping_total = models.DecimalField(
        default=5, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress,
                                        null=True, blank=True,
                                        on_delete=models.CASCADE)
    promo_code = models.OneToOneField(PromoCode, null=True, blank=True, on_delete=models.CASCADE)

    def _str_(self):
        return self.order_id
    
    def apply_promo_code(self, promo_code):
        if self.promo_code is None:
            self.promo_code = promo_code
            self.save()

            self.update_total()
            promo_code.use()


    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address
            
        shipping_address = self.user.shipping_address
        if shipping_address:
            self.update_shipping_address(shipping_address)

        return shipping_address

    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()

    def cancel(self):
        self.status = OrderStatus.CANCELED
        self.save()

    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()

    def update_total(self):
        self.total = self.get_total()
        self.save()

    def get_discount(self):
        if self.promo_code:
            return self.promo_code.discount
        return 0

    def get_total(self):
        return self.cart.total + self.shipping_total - decimal.Decimal(self.get_discount())

def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())

def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()



pre_save.connect(set_order_id, sender= Order)
pre_save.connect(set_total, sender= Order)

orders/views.py
from django.shortcuts import render
from .models import Order
from .utils import get_or_created_order
from carts.utils import get_or_create_cart
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from shipping_addresses.models import ShippingAddress

from.utils import destoy_order
from carts.utils import destroy_cart
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .utils import breadcrumb
from.mails import Mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.db.models.query import EmptyQuerySet
from .decorators import validate_cart_and_order
import threading

class OrderListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    template_name = 'orders/orders.html'

    def get_queryset(self):
        return self.request.user.orders_completed()

@login_required(login_url='login')
@validate_cart_and_order
def order(request, cart, order):
    

    return render(request, 'orders/order.html', {
        'cart' : cart,
        'order':order,
        'breadcrumb': breadcrumb()
    })

@login_required(login_url='login')
@validate_cart_and_order
def address(request, cart, order):
    
    
    shipping_address = order.get_or_set_shipping_address()
    can_choose_address = request.user.has_shipping_addresses()

    return render(request, 'orders/address.html', {
        'cart' : cart,
        'order' : order,
        'shipping_address' : shipping_address,
        'can_choose_address':can_choose_address,
        'breadcrumb' : breadcrumb(address=True)
    })

@login_required(login_url='login')
def select_address(request):
    shipping_addresses = request.user.addresses

    return render(request, 'orders/select_address.html', {
        'breadcrumb' : breadcrumb(address=True),
        'shipping_addresses' : shipping_addresses
        
    })

@login_required(login_url='login')
@validate_cart_and_order
def check_address(request,cart, order, pk):
    
    shipping_address = get_object_or_404(ShippingAddress, pk=pk)
    

    if request.user.id != shipping_address.user_id:
        return redirect('carts:cart')

    order.update_shipping_address(shipping_address)
    return redirect('orders:address')

@login_required(login_url='login')
@validate_cart_and_order
def confirm(request, cart, order):
    shipping_address = order.shipping_address
    if shipping_address is None:
        return redirect('orders:address')

    return render(request, 'orders/confirm.html',{
        'cart':cart,
        'order':order,
        'shipping_address': shipping_address,
        'breadcrumb': breadcrumb(address=True,confirmation=True)

    })


@login_required(login_url='login')
@validate_cart_and_order
def cancel(request, cart, order):
    if request.user.id != order.user_id:
        return redirect('carts:cart')

    order.cancel()

    destroy_cart(request)
    destoy_order(request)

    messages.error(request, 'Orden cancelada')
    return redirect('index')


@login_required(login_url='login')
@validate_cart_and_order
def complete(request, cart, order):
    if request.user.id != order.user_id:
        return redirect('carts:cart')

    order.complete()

    thread = threading.Thread(target=Mail.send_complete_order, args=(
        order, request.user
    ))
    thread.start()

    Mail.send_complete_order(order, request.user)

    destroy_cart(request) 
    destoy_order(request)

    messages.success(request, 'Compra completada exitosamente')
    return redirect('index')

orders/templates/orders/address.html
{% extends 'base.html '%}

{% block breadcrumb%}
{% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
<div class="col">
    {% if shipping_address %}
    <div class="h3">
        Recoge el pedido en el punto de entrega
    </div>
    <div class="">
        {% include 'shipping_addresses/snippets/shipping_address.html' %}

        <a href="{% url 'orders:confirm' %}" class="btn btn-warning mt-2">Entregar  aesta dirección</a>
        {% if can_choose_address %}      
        <div class="mt-2">
            <a href="{% url 'orders:select_address' %}">Otra dirección</a>
        </div>
        {% endif %}
       
    </div>
    {% else %}
    <div class="h3">
        Registra tu dirección de envío
    </div>
    <div class="">
        {% url 'orders:address' as next_url %} 
        <a href="{% url 'shipping_addresses:create' %}?next={{ next_url }}">Nueva dirección de envio</a>
    </div>
    {% endif %}
</div>
{% endblock %}

orders/templates/orders/confirm.html
{% extends 'base.html' %}

{% block breadcrumb %}
{% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
<div class="col-8">
    <div class="h3">
        Confirma tu pedido
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-4">
                    <div class="font-weight-bol">
                        Dirección de envio
                    </div>
                    <div class="card-text">
                        {{ shipping_address.address}}
                    </div>
                    <div class="card-text">
                        {{shipping_address.line1}}
                    </div>
                    <div class="card-text">
                        {{shipping_address.reference}}
                    </div>
                    <div class="card-text">
                        Codigo Postal {{shipping_address.postal_code}}
                    </div>

                </div>
                <div class="col-4">
                    <div class="font-weight-bold">
                        Método de pago
                    </div>
                    <div class="card-text">
                        Tarjeta terminación 4242
                    </div>
                </div>
                <div class="col-4">
                    <div class="font-weight-bold">
                        Código Promocional
                    </div>
                    <form id="promocode-form" action="{% url 'promo_codes:validate' %}">
                        <input type="text" name="code" value="{{ order.promo_code.code }}" class="form-control" placeholder="código promoción" {% if  order.promo_code %}readonly{% endif %}>
                    </form>
                    <div class="text-success" id="promocode-success" style="font-size:14px">
                        {% if order.promo_code %}
                            Código aplicado exitosamente
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-3">
        <div class="card">
            <div class="card-body">
                {% for product in cart.products.all %}
                  {% include 'orders/snippets/product.html' %}
                {% endfor %}
            </div>
        </div>
    </div>

</div>
<div class="col">
    {% url 'orders:complete' as next_url %}
    {% include 'orders/snippets/resume.html' with next_url=next_url %}
    <div class="mt-2">
        
        <a href="{% url 'orders:cancel' %}" class="btn btn-danger">Cancelar orden</a>

    </div>
</div>
{% endblock %}

{% block javascript %}
    <script>
        const form = document.getElementById('promocode-form')
        form.addEventListener('submit', function(e){
            e.preventDefault()
            
            const input = this.code
            const code = input.value
            const url = this.action + "?code=" + code
            const div_total = document.getElementById('order-total')
            const div_success = document.getElementById('promocode-success')
            console.log(url)

            fetch(url)
            .then(response=> response.json())
            .then(response=>{

                if(response.status === true){
                    //succes case
                    div_total.innerHTML = '$' + response.total

                    div_success.classList.remove('text-danger')
                    div_success.classList.add('text-success')
                    
                    div_success.innerHTML = 'Código aplicado exitosamente'

                    input.readOnly = true

                }else{
                    div_success.innerHTML = 'Código no valido'
                    div_success.classList.remove('text-success')
                    div_success.classList.add('text-danger')


                }
            })

        })
    </script>

{% endblock %}

orders/templates/orders/order.html
{%  extends 'base.html' %}
{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}

<div class="col-8">
    <div class="h3">
        Revisa tu pedido
    </div>
    <div class="card">
        <div class="card-body">
            {% for product in cart.products.all%}
                {% include 'orders/snippets/product.html' %}
            {% endfor %}
        </div>
    </div>
</div>
<div class="col">
    {% url 'orders:address' as next_url %}
    {% include 'orders/snippets/resume.html' with next_url=next_url %}
</div>

{% endblock  %}

orders/templates/orders/orders.html
{% extends 'base.html' %}

{% block content %}
    <div class="col">
        <div class="h3">
            Mis pedidos
        </div>
        <div class="">
            {% for order in object_list %}
                {% include 'orders/snippets/order.html' %}
            {% endfor %}

        </div>
    </div>
{% endblock %}

orders/templates/orders/select_address.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
    <div class="col">
        <div class="h3">Selecciona una dirección de envío</div>
        <div class="mt-2">
            {% for shipping_address in shipping_addresses %}
                <div class="card mb-2">
                    <div class="card-body">
                        <h5 class="card.title">{{ shipping_address.address }}</h5>
                        <p class="card-title">{{ shipping_address.postal_code }}</p>
                        <a href="{% url 'orders:check_address' shipping_address.pk %}" class="btn btn-warning"> Seleccionar dirección</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock%}