billing_profiles/urls.py
from django.urls import path

from . import views

app_name = 'billing_profiles'

urlpatterns=[
    path('nuevo', views.create, name='create')
]

carts/urls.py
from django.urls import path
from . import views


app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar',views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

facilito_store/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from products.views import ProductListView

urlpatterns = [
    path('',ProductListView.as_view(), name='index'),
    path('admin/', admin.site.urls),

    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('codigos/', include('promo_codes.urls')),
    path('pagos/', include('billing_profiles.urls')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name= 'order'),
    path('dirección', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds'),


]

shipping_addresses/urls.py
from django.urls import path
from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('nuevo', views.create, name='create'),
    path('editar/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('eliminar/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
   
    <!--  <link rel="stylesheet" href="{% static 'css/style.css' %}">-->
    {% block css %}
    {% endblock %}
</head>
<body>

    {% include 'navbar.html'%}

    <div class="container">
       {% include 'messages.html' %}

       {% block breadcrumb %}
       {% endblock %}

        <div class="row mt-4">
            {% block content %}
            {% endblock %}

        </div>
    </div>
    
</body>

<script src="https://kit.fontawesome.com/2d5cd449a3.js" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<!--<script src="{% static 'js/main.js' %}"></script>-->
{% block javascript %}


{% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
  
<div class="col">
    <h4 class="text-center">{{message}}</h4>
    {% include 'products/snippets/search.html' %}
    {% include  'products/snippets/list.html' %}    
</div>

{% endblock %}

      
  

templates/messages.html
{% if messages %}
{% for message in messages %}
    <div class="alert {% if message.tags == 'success'%}alert-success{% else %}alert-danger {% endif %}">
            <button type="button" class="close" data-dismiss="alert">x</button>
            {{ message }}
        </div>
{% endfor %}
{% endif %}

templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}
{%   url 'carts:cart' as cart   %}
{%   url 'shipping_addresses:shipping_addresses' as shipping_addresses   %}
{% url 'orders:completeds' as completeds %}
{% url 'billing_profiles:create' as billing_profiles %}
<!-- con la clase active le se permite conocer al usuario en que lugar se encuentra-->

<nav class="navbar navbar-expand-md  bg-dark navbar-dark">
    <a href="{% url 'index'  %}" class="navbar-brand">facilito store</a>

    <button type="button" name="button" class="navbar-toggler navbar-toggler-right " data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navb" class="navbar-collapse collapse hide">

        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == cart%}active{% endif %}">
                <a class="nav-link" href="{{ cart }}">
                    Mi carrito<span class="fas fa-shopping-cart"></span>
                </a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item {% if request.path == shipping_addresses%}active{% endif %}">
                    <a class="nav-link" href="{{ shipping_addresses }}">
                        Mis direcciones<span class="fas fa-location-arrow"></span>
                    </a>
                </li>

                <li class="nav-item {% if request.path == completeds %}active{% endif %}">
                    <a class="nav-link" href="{{ completeds }}">
                        Mis pedidos<span class="fas fa-shipping-fast"></span>
                    </a>
                </li>
                <li class="nav-item {% if request.path == billing_profiles %}active{% endif %}">
                    <a class="nav-link" href="{{ billing_profiles }}">
                        Mis metodos de pago<span class="fab fa-cc-stripe"></span>
                    </a>
                </li>
            {% endif %}
            
        </ul>

        <ul class="nav navbar-nav ml-auto">

            <!--se hace uso del objeto user par usuarios autenticados-->
            {% if user.is_authenticated %}
                <li class="navbar-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="fas fa-sign-in-alt"></span>
                        Logout</a>
                </li>
            {% else %}

                <li class="navbar-item {% if request.path == login %}active{% endif %}">
                    <a href="{{ login }}" class="nav-link">
                        <span class="fas fa-user"></span>
                        Login</a>
                </li>

                <li class="navbar-item  {% if request.path == register %}active{% endif %}">
                    <a href="{% url 'register' %}" class="nav-link">
                        <span class="fas fa-user-plus"></span>
                        Registro</a>
                </li>
            {% endif %}

            
        </ul>
        
    </div>
</nav>